name: Main Branch CI/CD.

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "Deploy kar raha hun 🚀"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i --location=global yarn
      - run: yarn
      - run: yarn test
      - run: echo "Deploy done... 🤯"